FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["ECommercePlatform/ECommercePlatform.csproj", "ECommercePlatform/"]
RUN dotnet restore "ECommercePlatform/ECommercePlatform.csproj"
COPY . .
WORKDIR "/src/ECommercePlatform"
RUN dotnet build "ECommercePlatform.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ECommercePlatform.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ECommercePlatform.dll"]
